### ISSUE TITLE
Error while asking it any thing

### ISSUE THREAD

**Issue by ansarimohammed422** [BrianJr03/Issa-Chat-App#13]
ERROR: You exceeded your current quota, please check your plan and billing details.

**Comment by BrianJr03** [comment]
> ERROR: You exceeded your current quota, please check your plan and billing details.

@ansarimohammed422 It looks like you need to update your OpenAI plan and billing details. You've gone over your limit sadly.

**Comment by ansarimohammed422** [comment]
What limit

**Comment by BrianJr03** [comment]
https://platform.openai.com/account/usage
