### ISSUE TITLE
[Feature] Add possibility to Clear conversation

### ISSUE THREAD

**Issue by carnager** [BrianJr03/Issa-Chat-App#26]
Right now it's only possible to clear individual entries from a chat history. A button to clear the whole history and start a fresh chat would be a good way to quickly start anew.

**Comment by BrianJr03** [comment]
There is a way to clear everything. It's in Settings. "Delete all chats"

**Comment by carnager** [comment]
Sure, but once multi-chat is implemented (as tracked [here](https://github.com/BrianJr03/Issa-Chat-App/issues/25), it might be a good idea to be able to delete single chats.

**Comment by BrianJr03** [comment]
I'm not quite understanding, you can already delete single chats by single tapping and using the delete icon. Is that what you meant? 

Nonetheless, I appreciate the feedback. Funny thing is, this started as a demo app to play with the API but somehow here we are. I figured this would be a nice intro to open source and F Droid has been on my radar.

**Comment by carnager** [comment]
> I'm not quite understanding, you can already delete single chats by single tapping and using the delete icon. Is that what you meant?
> 
> Nonetheless, I appreciate the feedback. Funny thing is, this started as a demo app to play with the API but somehow here we are. I figured this would be a nice intro to open source and F Droid has been on my radar.

Maybe I am blind, but right now I can only delete individual entries of a chat one by one. I dont see a way to delete the full history of a single chat.

**Comment by BrianJr03** [comment]
![Screenshot_2023-04-08-08-27-50-93_8ffde6dde5cd9c18c350501a92d62c70.jpg](https://user-images.githubusercontent.com/55070185/230721063-ad33dcb0-9dd7-4119-87f5-9001c2489f8e.jpg)

Here is a screenshot of the Settings dialog. You need to long press the options in red to confirm the action.

**Comment by BrianJr03** [comment]
Here is the `Delete All Chats` option in `Settings`. You must long press to confirm. 

![Screenshot_2023-04-08-08-27-50-93_8ffde6dde5cd9c18c350501a92d62c70.jpg](https://user-images.githubusercontent.com/55070185/230721362-71afc1da-075e-47f5-b590-e7d6a35c8a8a.jpg)
