### ISSUE TITLE
Suggestion to fix "long context bug"

### ISSUE THREAD

**Issue by Gomibako7** [BrianJr03/Issa-Chat-App#31]
I have noticed that when a contextual prompt is too long, the UI does not allow for scrolling down to access other settings. I believe this could be improved by creating a separate menu for the context, to avoid any issues with UI navigation.

This issue is easily reproducible by using a very extensive prompt (600 characters or more)

Thank you 

Best regards

**Comment by BrianJr03** [comment]
I'll get on that soon and have an update by today or tomorrow. Thanks for the feedback!

**Comment by BrianJr03** [comment]
I made [changes](https://github.com/BrianJr03/Issa-Chat-App/releases/tag/v1.6.1) and now there is a separate dialog for conversational context. Let me know if I should increase the max character count. It is currently 600.

**Comment by Gomibako7** [comment]
The issue is now resolved but the 600 character limit defeats the purpose of the fix, which was to allow extremely long contextual prompts (example of use case, jailbreak prompts, elaborated roleplay etc).

I suggest allowing the highest possible amount of characters.

Thanks for taking the time

**Comment by BrianJr03** [comment]
Gotcha, I'll have a fix out soon

**Comment by BrianJr03** [comment]
@Gomibako7 I have a fix and I believe it's what you're looking for. Just download the updated apk from [v1.6.1](https://github.com/BrianJr03/Issa-Chat-App/releases/tag/v1.6.1)
